import { formatTimestamp } from "../../shared/util/datetime";
import {
  buildWaitContextNarrative
} from "../../runStatus";
import type { SourceAsset } from "../sources/model";
import type { Workspace } from "../workspace/model";
import {
  summarizeText,
  readRecoveryTargets,
  formatResearchAnswerStatus,
  formatRecoveryTargetLabels,
  formatRecoveryTargetColumns,
  buildCurrentRecoveryNarrative,
  buildReportRecoveryNarrative,
  buildArtifactRecoveryNarrative,
  buildSourceOriginBadge,
  buildResearchSourceLabel,
  buildRunCheckpointNarrative,
  buildRunContinuityBaselineLabel,
  buildRunContinuityNarrative,
  buildResearchTaskRuntimeSnapshot,
  researchHistoryFilterLabel,
  buildRunPrimaryTone,
  timelineStageLabel,
  currentRunStageLabelFromSummary,
  sameStageLabel,
  buildRunSignalChips
} from "./presentation";
import type { ResearchWorkbenchController } from "./useResearchWorkbenchController";

export type ResearchWorkbenchViewProps = ReturnType<typeof buildResearchWorkbenchProps>;

export function buildResearchWorkbenchProps(
  research: ResearchWorkbenchController,
  workspace: Workspace | null,
  sources: SourceAsset[],
  isBusy: boolean
) {
  const sourceById = new Map(sources.map((source) => [source.source_id, source] as const));

  return {
    isBusy,
    sidebar: {
      summarizedResearchQuestion: research.summarizedResearchQuestion,
      summarizedResearchGoal: research.summarizedResearchGoal,
      researchDeliverableFormat: research.researchDeliverableFormat,
      researchProfile: research.researchProfile,
      researchDepth: research.researchDepth,
      researchType: research.researchType,
      researchRetrievalMode: research.researchRetrievalMode,
      researchScopeCount: research.researchScopeCount,
      researchQuestion: research.researchQuestion,
      setResearchQuestion: research.setResearchQuestion,
      researchGoal: research.researchGoal,
      setResearchGoal: research.setResearchGoal,
      setResearchProfile: research.setResearchProfile,
      setResearchDeliverableFormat: research.setResearchDeliverableFormat,
      researchTimeRange: research.researchTimeRange,
      setResearchTimeRange: research.setResearchTimeRange,
      setResearchDepth: research.setResearchDepth,
      setResearchType: research.setResearchType,
      setResearchRetrievalMode: research.setResearchRetrievalMode,
      researchConstraintsText: research.researchConstraintsText,
      setResearchConstraintsText: research.setResearchConstraintsText,
      startDeepResearch: research.startDeepResearch,
      workspace,
      loadResearchRunHistory: research.loadResearchRunHistory,
      sources,
      selectedResearchSourceIds: research.selectedResearchSourceIds,
      currentSavedReportSource: research.currentSavedReportSource,
      focusedResearchSourceId: research.focusedResearchSourceId,
      toggleResearchScope: research.toggleResearchScope,
      setFocusedResearchSourceId: research.setFocusedResearchSourceId,
      buildSourceOriginBadge,
      researchScopeSources: research.researchScopeSources,
      currentSavedReportSourceInScope: research.currentSavedReportSourceInScope,
      researchRuns: research.researchRuns,
      filteredResearchRuns: research.filteredResearchRuns,
      researchHistoryFilter: research.researchHistoryFilter,
      setResearchHistoryFilter: research.setResearchHistoryFilter,
      researchHistoryFilterLabel,
      researchTimelineMilestones: research.researchTimelineMilestones,
      runContinuityBaselineById: research.runContinuityBaselineById,
      buildRunContinuityBaselineLabel,
      buildRunContinuityNarrative,
      currentResearchRunSummary: research.currentResearchRunSummary,
      sameStageLabel,
      timelineStageLabel,
      currentRunStageLabelFromSummary,
      openResearchRunHistoryItem: research.openResearchRunHistoryItem,
      summarizeText,
      buildRunCheckpointNarrative,
      formatTimestamp,
      researchTimelinePath: research.researchTimelinePath,
      buildRunSignalChips,
      buildRunPrimaryTone,
      readRecoveryTargets,
      currentResearchRunId: research.currentResearchRunId,
      formatRecoveryTargetLabels,
      formatRecoveryTargetColumns,
      buildCurrentRecoveryNarrative
    },
    report: {
      currentResearchRun: research.currentResearchRun,
      currentResearchCollection: research.currentResearchCollection,
      formatTimestamp,
      buildReportRecoveryNarrative,
      currentResearchRunSummary: research.currentResearchRunSummary,
      researchReportStructure: research.researchReportStructure,
      currentRecoveryTargets: research.currentRecoveryTargets,
      refreshCurrentResearchRun: research.refreshCurrentResearchRun,
      currentResearchRunId: research.currentResearchRunId,
      exportResearchReportMarkdown: research.exportResearchReportMarkdown,
      saveResearchReportAsSource: research.saveResearchReportAsSource,
      setResearchDetailOpen: research.setResearchDetailOpen,
      formatResearchAnswerStatus,
      currentFinalAnswer: research.currentFinalAnswer,
      resultSnapshotTitle: research.resultSnapshotTitle,
      resultSnapshotNarrative: research.resultSnapshotNarrative,
      currentExecutiveSummary: research.currentExecutiveSummary,
      currentResearchSourceEvidenceSummary: research.currentResearchSourceEvidenceSummary,
      currentVerifiedFindings: research.currentVerifiedFindings,
      currentIntentCompletionContract: research.currentIntentCompletionContract,
      currentKeyTakeaways: research.currentKeyTakeaways,
      currentUncertaintyAndRisks: research.currentUncertaintyAndRisks,
      buildResearchSourceLabel,
      sourceById,
      summarizeText,
      currentSavedReportSource: research.currentSavedReportSource,
      currentEvidenceHighlights: research.currentEvidenceHighlights,
      researchClosedLoopState: research.researchClosedLoopState,
      buildArtifactRecoveryNarrative,
      currentRunSummaryRecoveryTargets: research.currentRunSummaryRecoveryTargets,
      currentSavedReportSourceAsset: research.currentSavedReportSourceAsset,
      currentSavedReportSourceInScope: research.currentSavedReportSourceInScope,
      removeResearchSourceFromScope: research.removeResearchSourceFromScope,
      addResearchSourceToScope: research.addResearchSourceToScope,
      setFocusedResearchSourceId: research.setFocusedResearchSourceId,
      researchTimelinePath: research.researchTimelinePath
    },
    statusPanel: {
      currentResearchRunSummary: research.currentResearchRunSummary,
      currentResearchWaitContext: research.currentResearchWaitContext,
      currentResearchWaitSignals: research.currentResearchWaitSignals,
      currentResearchWaitDetails: research.currentResearchWaitDetails,
      latestResearchTask: research.latestResearchTask,
      latestResearchTaskWaitSignals: research.latestResearchTaskWaitSignals,
      latestResearchTaskWaitDetails: research.latestResearchTaskWaitDetails,
      latestResearchProgressEvent: research.latestResearchProgressEvent,
      currentResearchRun: research.currentResearchRun,
      buildWaitContextNarrative,
      buildResearchTaskRuntimeSnapshot,
      setResearchDetailOpen: research.setResearchDetailOpen
    },
    detail: {
      researchDetailOpen: research.researchDetailOpen,
      currentResearchRun: research.currentResearchRun,
      selectedResearchCheckpointNo: research.selectedResearchCheckpointNo,
      selectedResearchCheckpoint: research.selectedResearchCheckpoint,
      compareResearchCheckpointNo: research.compareResearchCheckpointNo,
      compareResearchCheckpoint: research.compareResearchCheckpoint,
      setResearchDetailOpen: research.setResearchDetailOpen,
      refreshCurrentResearchRun: research.refreshCurrentResearchRun,
      saveResearchReportAsSource: research.saveResearchReportAsSource,
      openResearchWorkbench: research.openResearchWorkbench,
      removeResearchSourceFromScope: research.removeResearchSourceFromScope,
      addResearchSourceToScope: research.addResearchSourceToScope,
      setFocusedResearchSourceId: research.setFocusedResearchSourceId,
      openResearchCheckpoint: research.openResearchCheckpoint,
      updateResearchCheckpointComparison: research.updateResearchCheckpointComparison,
      resumeResearchFromCheckpoint: research.resumeResearchFromCheckpoint
    }
  };
}
