package com.noteweave.graph.dto;

public enum KnowledgeGraphEdgeType {
    WIKI_LINK,
    WIKI_SOURCE_ARTIFACT,
    WIKI_SOURCE_MESSAGE,
    WIKI_CITES_DOCUMENT,
    ARTIFACT_SOURCE_DOCUMENT,
    ARTIFACT_SOURCE_MESSAGE,
    ARTIFACT_SOURCE_ARTIFACT,
    ARTIFACT_CITES_DOCUMENT,
    CHAT_CITES_DOCUMENT,
    CHAT_GENERATES_ARTIFACT,
    ARTIFACT_IN_SESSION,
    ARTICLE_RELATES_CONCEPT,
    CONCEPT_RELATES_CONCEPT,
    SYNTHESIS_RELATES_CONCEPT,
    SYNTHESIS_SOURCE_ARTIFACT,
    ARTIFACT_RELATES_CARD,
    ARTICLE_CITES_DOCUMENT,
    CONCEPT_CITES_DOCUMENT,
    SYNTHESIS_CITES_DOCUMENT
}
